### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by sreedevi111** [sketchomania/news-app#1]
In src/api/ services.tsx, From where CONFIG is imported? Folder named config as well as file named config is not there in code

**Comment by sketchomania** [comment]
I should mention it in readme
You can create a config file at src/config/config.js and paste the following in to the file 
```js
export const CONFIG = {
  API_KEY: 'your_api_key',
  ENDPOINT: 'https://newsapi.org/v2/',
  COUNTRY: 'in',
};
```
