### ISSUE TITLE
class NewsCard got error

### ISSUE THREAD

**Issue by justin17757** [sketchomania/news-app#2]
This is the error of NewsCard class. It seem problem with the parameter "data"

Type '({ data }: NewsCardProps) => Element | undefined' is not assignable to type 'FC<NewsCardProps>'.
Type 'Element | undefined' is not assignable to type 'ReactElement<any, any> | null'.
Type 'undefined' is not assignable to type 'ReactElement<any, any> | null'.t

**Comment by sketchomania** [comment]
This was happening because a issue in return statement 
here:

```js
// line: 77
 if (!(urlToImage && description && title)) {
    return;
  }
```
