### ISSUE TITLE
Config file Not found

### ISSUE THREAD

**Issue by PR-Here** [sketchomania/news-app#3]
Config file not fount with in the project
<img width="434" alt="Screenshot 2023-04-07 at 6 09 05 PM" src="https://user-images.githubusercontent.com/89129280/230610309-7daedb4d-33a4-4068-b18b-76f767cec4fc.png">

**Comment by sketchomania** [comment]
I have mentioned **Setup steps** in the README file 
Read here: https://github.com/sketchomania/news-app#react-native-setup
